function  Continents = CDF_nat2cont(countries)

    African_countries = {'Algeria'
                        'Angola'
                        'Benin'
                        'Botswana'
                        'Burkina Faso'
                        'Burundi'
                        'Cabo Verde'
                        'Cape Verde'
                        'Cameroon'
                        'Central African Republic'
                        'Chad'
                        'Comoros'
                        'Congo'
                        'Republic of the Congo'
                        'Democratic Republic of the Congo'
                        'Djibouti'
                        'Egypt'
                        'Equatorial Guinea'
                        'Eritrea'
                        'Eswatini'
                        'Ethiopia'
                        'Gabon'
                        'Gambia'
                        'Ghana'
                        'Guinea'
                        'Guinea-Bissau'
                        'Ivory Coast'
                        'Kenya'
                        'Lesotho'
                        'Liberia'
                        'Libya'
                        'Madagascar'
                        'Malawi'
                        'Mali'
                        'Mauritania'
                        'Mauritius'
                        'Morocco'
                        'Mozambique'
                        'Namibia'
                        'Niger'
                        'Nigeria'
                        'Rwanda'
                        'Sao Tome and Principe'
                        'Senegal'
                        'Seychelles'
                        'Sierra Leone'
                        'Somalia'
                        'South Africa'
                        'South Sudan'
                        'Sudan'
                        'Tanzania'
                        'United Republic of Tanzania'
                        'Togo'
                        'Tunisia'
                        'Uganda'
                        'Zambia'
                        'Zimbabwe'
                        'Canary Islands'
                        'Ceuta'
                        'French Southern and Antarctic Lands'
                        'Madeira'
                        'Mayotte'
                        'Melilla'
                        'Pelagie Islands'
                        'Plazas de Soberania'
                        'Reunion'
                        'Saint Helena, Ascension and Tristan da Cunha'
                        'Socotra Archipelago'};

    Asian_countries = {'Afghanistan'
                    'Armenia'
                    'Azerbaijan'
                    'Bahrain'
                    'Bangladesh'
                    'Bhutan'
                    'British Indian Ocean Territory'
                    'Brunei Darussalam'
                    'Brunei'
                    'Cambodia'
                    'China'
                    'Cyprus'
                    'Egypt'
                    'Georgia'
                    'Hong Kong'
                    'India'
                    'Indonesia'
                    'Iran'
                    'Iran Islamic Republic of'
                    'Iraq'
                    'Israel'
                    'Japan'
                    'Jordan'
                    'Kazakhstan'
                    'Kuwait'
                    'Kyrgyzstan'
                    'Laos'
                    'Lao People''s Democratic Republic'
                    'Lebanon'
                    'Macau'
                    'Malaysia'
                    'Maldives'
                    'Mongolia'
                    'Myanmar'
                    'Nepal'
                    'North Korea'
                    'Oman'
                    'Pakistan'
                    'Palestine'
                    'Philippines'
                    'Qatar'
                    'Russia'
                    'Saudi Arabia'
                    'Singapore'
                    'South Korea'
                    'Korea, Republic of'
                    'Sri Lanka'
                    'Syria'
                    'Taiwan'
                    'Tajikistan'
                    'Thailand'
                    'Timor-Leste'
                    'East Timor'
                    'Turkey'
                    'Turkmenistan'
                    'United Arab Emirates'
                    'Uzbekistan'
                    'Vietnam'
                    'Viet Nam'
                    'Yemen'};

    European_countries = {'Albania'
                        'Andorra'
                        'Armenia'
                        'Austria'
                        'Azerbaijan'
                        'Belarus'
                        'Belgium'
                        'Bosnia and Herzegovina'
                        'Bulgaria'
                        'Croatia'
                        'Cyprus'
                        'Czechia'
                        'Czech'
                        'Czech Republic'
                        'Denmark'
                        'Estonia'
                        'Finland'
                        'France'
                        'Georgia'
                        'Germany'
                        'Greece'
                        'Hungary'
                        'Iceland'
                        'Ireland'
                        'Italy'
                        'Kazakhstan'
                        'Latvia'
                        'Liechtenstein'
                        'Lithuania'
                        'Luxembourg'
                        'Malta'
                        'Moldova'
                        'Republic of Moldova'
                        'Monaco'
                        'Montenegro'
                        'Netherlands'
                        'North Macedonia'
                        'Norway'
                        'Poland'
                        'Portugal'
                        'Romania'
                        'Russia'
                        'San Marino'
                        'Serbia'
                        'Slovakia'
                        'Slovenia'
                        'Spain'
                        'Sweden'
                        'Switzerland'
                        'Turkey'
                        'Ukraine'
                        'United Kingdom'
                        'Vatican City'
                        'Åland'
                        'Channel Islands'
                        'Faroe Islands'
                        'Gibraltar'
                        'Guernsey'
                        'Isle of Man'
                        'Jersey'
                        'Kosovo'
                        'Northern Cyprus'
                        'Northern Ireland'
                        'Svalbard'};

    NA_countries = {'Antigua and Barbuda'
                    'Bahamas'
                    'Barbados'
                    'Belize'
                    'Canada'
                    'Costa Rica'
                    'Cuba'
                    'Dominica'
                    'Dominican Republic'
                    'El Salvador'
                    'Grenada'
                    'Guatemala'
                    'Haiti'
                    'Honduras'
                    'Jamaica'
                    'Mexico'
                    'Nicaragua'
                    'Panama'
                    'Saint Kitts and Nevis'
                    'Saint Lucia'
                    'Saint Vincent and the Grenadines'
                    'Trinidad and Tobago'
                    'United States of America'
                    'United States'
                    'Anguilla'
                    'Aruba'
                    'Bermuda'
                    'Bonaire'
                    'British Virgin Islands'
                    'Cayman Islands'
                    'Clipperton Island'
                    'Curaçao'
                    'Greenland'
                    'Guadeloupe'
                    'Martinique'
                    'Montserrat'
                    'Navassa Island'
                    'Puerto Rico'
                    'Saba'
                    'Saint Barthélemy'
                    'Saint Martin'
                    'Saint Pierre and Miquelon'
                    'Sint Eustatius'
                    'Sint Maarten'
                    'Turks and Caicos'};

    Ocean_countries = {'Australia'
                    'Fiji'
                    'Kiribati'
                    'Marshall Islands'
                    'Micronesia'
                    'Nauru'
                    'New Zealand'
                    'Palau'
                    'Papua New Guinea'
                    'Samoa'
                    'Solomon Islands'
                    'Tonga'
                    'Tuvalu'
                    'Vanuatu'
                    'Cook Islands'
                    'New Caledonia'};

    SA_countries = {'Argentina'
                    'Bolivia'
                    'Brazil'
                    'Chile'
                    'Colombia'
                    'Ecuador'
                    'Guyana'
                    'Paraguay'
                    'Peru'
                    'Suriname'
                    'Uruguay'
                    'Venezuela'
                    'Bouvet Island'
                    'Falkland Islands'
                    'French Guinea'
                    'Nueva Esparta'
                    'South Georgia and the South Sandwich Islands'};
            
    Continent_id = nan(numel(countries),1);
    l = ismember(countries,African_countries);   Continent_id(l) = 1;
    for ct = find(l'),    Continents{ct,1} = 'Africa';   end
    l = ismember(countries,Asian_countries);     Continent_id(l) = 2;
    for ct = find(l'),    Continents{ct,1} = 'Asia';   end
    l = ismember(countries,European_countries);  Continent_id(l) = 3;
    for ct = find(l'),    Continents{ct,1} = 'Europe';   end
    l = ismember(countries,NA_countries);        Continent_id(l) = 4;
    for ct = find(l'),    Continents{ct,1} = 'North America';   end
    l = ismember(countries,SA_countries);        Continent_id(l) = 5;
    for ct = find(l'),    Continents{ct,1} = 'South America';   end
    l = ismember(countries,Ocean_countries);     Continent_id(l) = 6;
    for ct = find(l'),    Continents{ct,1} = 'Oceanic';   end
    
end